trigger:
- main

pool:
  name: default

stages:
  - stage: VersionBump
    pool:
      name: default
      demands: Web
    displayName: Version Bump
    jobs:
      - job: VersionBumpJob
        displayName: VersionBump
        steps:
          - checkout: self

          - task: CmdLine@2
            displayName: "Pull Latest Changes"
            inputs:
              script: |
                git fetch origin $(Build.SourceBranchName)
                git reset --hard FETCH_HEAD
          
          - powershell: |
              $buildName = & "C:\Users\buildagent\AppData\Local\Pub\Cache\bin\cider" bump patch
              Write-Host "Output from cider command: $buildName"
              Write-Host "##vso[build.updatebuildnumber]$buildName"
            displayName: 'Bump Version and Set Build Name'
            condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')

          - task: CmdLine@2
            displayName: 'Set Git Config and Push Version Change'
            condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
            inputs:
              script: |
                git commit -a -m "Vesion patch [skip ci]"
                git tag -a $(Build.BuildNumber) -m "Version $(Build.BuildNumber)"
                git config --global user.email "buildAgent@gsd-software.com"
                git config --global user.name "Build Agent"
                git push origin HEAD:$(Build.SourceBranchName) --tags
                git push --set-upstream origin HEAD:$(Build.SourceBranchName)

          - task: CopyFiles@2
            displayName: "Copy to artifact staging directory"
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)'
              Contents: 'README.md'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
              OverWrite: true

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'gsd-utilities'
              publishLocation: 'Container'  

  - stage: BuildExampleApp
    pool:
      name: default
      demands: Web
    displayName: Build Example App
    dependsOn: VersionBump
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - job: BuildExampleAppJob
        displayName: Web
        steps:
        - checkout: self

        - task: CmdLine@2
          displayName: "Pull Latest Changes"
          inputs:
            script: |
              git fetch origin $(Build.SourceBranchName)
              git reset --hard FETCH_HEAD

        - task: CmdLine@2
          displayName: "Clean project"
          inputs:
            script: 'flutter clean'
            workingDirectory: '$(Build.SourcesDirectory)\example'

        - task: CmdLine@2
          displayName: "Resolve dependencies"
          inputs:
            script: 'flutter pub get'
            workingDirectory: '$(Build.SourcesDirectory)\example'

        - task: CmdLine@2
          displayName: "Run build Web"
          inputs:
            script: 'flutter build web --release --no-tree-shake-icons'
            workingDirectory: '$(Build.SourcesDirectory)\example'

        - task: CopyFiles@2
          displayName: "Copy to artifact staging directory"
          inputs:
            SourceFolder: '$(Build.SourcesDirectory)\example\build\web'
            Contents: '**'
            TargetFolder: '$(Build.ArtifactStagingDirectory)\web-example'
            OverWrite: true

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'gsd-utilities'
            publishLocation: 'Container'

